#!/usr/bin/env node 
 
//author  : Umar aka jukoo  j_umar@outlook.com   <github.com/jukoo> 
//menu  : require(".deprecated/menu") , 

__KERNEL__v1 :   
module 
["exports"] =  {
    
    ["@libs"]  :  { 
         utils : require("./libs/utils"), 
         tcmd  : require("./libs/command")  
    } ,
    ["@node_module"] : { 
        url    : require("url"), 
        path   : require("path"), 
        fs     : require("fs"),
        os     : require("os") 
    },
    ["@config"]: {
        defconf : require("./config") 
    } , 
   ["@extra"]  :  {  
       xpress  : require("express"), 
       xpressfu: require("express-fileupload") , 
       io_socket:  require("socket.io")
   }
}
